---
title: "R Notebook"
output: html_notebook
---

```{r}
source("/Users/root1/Documents/DAC_Project/R/config.R")
```


```{r}
data = readFromParquet(glue(PATH_DB,"parquet"))
```


```{r}
data = readFromParquet(glue(PATH_DB,"parquet"))

train_labels = read_csv(getFilePath("train_labels")) 
train_labels[,'customer_ID'] =  as.integer(match(train_labels$customer_ID, getUniqueCustomerID("train_data")))


data[,'target'] = merge(x = data[,'customer_ID'], y = train_labels, by = "customer_ID", all.x = TRUE)$target
```


```{r}
N = nrow(data)

i_partitions = partition(1:N, p = c(train = 0.7, valid = 0.2, test = 0.1))

# Assign data frames, shuffle order
x_train = data[sample(i_partitions$train),] 
x_val = data[sample(i_partitions$valid),] 
x_test = data[sample(i_partitions$test),] 
rm(data)
```


```{r}
split(n, cut(seq_along(n), chunks, labels = FALSE))[[1]]
```

```{r}
writeParaquetTVT = function(data,TVT){
    chunks = 20
    n = 1:nrow(data)
    splits = split(n, cut(seq_along(n), chunks, labels = FALSE))
    
    for(j in 1:chunks){
      write_parquet(
        dplyr::slice(data, splits[[j]]), 
        glue(PATH_DB, "parquetTVT/",TVT,"/",TVT,"_",j,".parquet")
      )
    }
}

writeParaquetTVT(x_train, "train")
writeParaquetTVT(x_val, "validation")
writeParaquetTVT(x_test, "test")
```

```{r}
fractions(INTERVALS$interval)
```

```{r}
INTERVALS$interval[INTERVALS$interval %>% is.na] = 0
```


```{r}
qwe = colnames(x_train)[which(!colnames(x_train) %in% INTERVALS$column)]
```
c('D_70',
'R_11',
'R_15',
'D_91',
'D_107',
'D_109')
```{r}
missingCols = c('D_70',
'R_11',
'R_15',
'D_91',
'D_107',
'D_109')
```


```{r}
missingCols %in% columns
```


```{r}
missingCols %in%  INTERVALS$column
```


```{r}
x_train[,missingCols]
```

```{r}
cols_int = c('B_30', 'B_38', 'D_114', 'D_116', 'D_117', 'D_120', 'D_126', 'D_66', 'D_68')
```

```{r}
fractions(0.04347826)
```

```{r}
start = seq(1, nrow(data), chunkSize-1)
end = start + chunkSize - 1
```


```{r}
nrow(data) - 3871981
```

```{r}
d = 1:30
i = 1
split(1:nrow(data), ceiling(seq_along(d)/20))
```

```{r}
chunks = 20
chunkSize = floor(nrow(data)/chunks)
rem = nrow(data) %% chunkSize
```


```{r}
gc()
```


