# Abbreviations 

\spacing{1.1}

```{r, echo=FALSE, message=FALSE, results='hide'}
library(knitr)
abbrev <- matrix(data = c("AI", "Artificial Intelligence",
             "AMEX", "American Express",
             "AUC", "Area Under the Curve",             
             "DNN", "Deep Neural Network",
             "EDA", "Exploratory Data Analysis",
             "GRU", "Gated Recurrent Unit",
             "K-S", "Kolmogorov-Smirnov",
             "LR", "Logistic Regression",
             "ML", "Machine Learning",
             "NN", "Neural Network",
             "RF", "Random Forest",             
             "RNN", " Recurrent Neural Network",
             "ROC", "Receiver Operating Characteristic",
             "SVM", "Support Vector Machines",
             "TNR", "True Negative Rate",
             "TPR", "True Positive Rate"),
             byrow = T, ncol = 2)
```


```{r, echo=FALSE}
kable(abbrev, col.names = c("Abbreviation", "Meaning" ),label="Abbreviations", caption ="List of Abbrevivations")
```



