\spacing{1.1}

# Introduction

A credit card is a financial instrument issued by banks and other financial institutions with a pre-set credit limit allowing customers to make cashless transactions. Each month or at different intervals, a statement is issued by the credit card provider with details of spending history, the interest charged, balance, and payment deadlines. 
\vspace{.1 cm}

As of May 2022, there were 1.5 million active credit cards in circulation in Ireland with daily spending exceeding \texteuro 1 million.[^1]. Further to that, according to research conducted by the Central Statistics Office in 2018, 12.7% of all households have credit card debt but is 21.0% for households with two adults and one to three children under 18.[^2]
\vspace{.1 cm}

[^1]: <https://www.centralbank.ie/statistics/data-and-analysis/credit-and-debit-card-statistics/daily-credit-and-debit-card-statistics>

[^2]: <https://www.cso.ie/en/releasesandpublications/ep/p-hfcs/householdfinanceandconsumptionsurvey2018/debtandcredit/>

A default event concerning a credit card occurs if a customer does not pay the amount due within 120 days of their latest statement date. However, the deadline can depend on the issuing institution. The most significant risk to lenders is a large and unexpected number of customers failing to meet their credit repayment obligations. This is known as credit default risk. Credit default prediction is central to managing risk in a consumer lending business. Financial institutions are legally obligated to create models that predict credit defaults. Credit card default prediction is based on historical data of credit card customers. The use of models to predict and analyse credit card customer default behaviour is a typical classification problem. These models advise the banks capital requirements, which ensure that the bank can absorb losses brought about by a significant increase in credit defaults. Credit default prediction also allows lenders to optimize lending decisions, which leads to a better customer experience and sound business economics. Current models exist to help manage risk but is it possible to create better models that outperform those currently in use? Given that banking portfolios can be worth billions, even marginal improvements in preventing and reducing defaults can be considered significant. 
\vspace{.1 cm}

The big data paradigm has revolutionised the banking industry, changing the way financial institutions operate. Developments in technology has revolutionized the customer experience and has also granted access to a ever-growing volume of structured and unstructured information. Institutions can leverage this new information in many ways including predicting credit default. There have been advances in Machine Learning (ML) techniques such as representation learning methods e.g. Neural Networks, ensemble learning methods such as Random Forest and linear separating methods e.g. Support Vector Machines. These models have yet to be widely deployed because of their opaque nature i.e. Black-Box methods. From a regulation perspective, transparency and explainability are necessary when deploying credit default prediction models in practice. However, they may still provide value to financial institutions and may in the future be accepted as valid, clear and sound methods for predicting credit card default. 
\vspace{.1 cm}

The aim of this project is to apply a range of advanced machine learning techniques to predict credit card default using the historical data of credit card customers. The following report describes the process undertaken to compare a number of models. Beginning with an industrial size dataset, cleansing and formatting the data before using it to train, tune and evaluate the chosen models based on the historical data of credit card customers.
